package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * Approval generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "APPROVAL")
public class Approval extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private ApprovalStatus approvalStatus;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private ApprovalLevel approvalLevel;
	
	@FormElement(type = FormType.DATE, listed = true)
	private Date date;
	
	@FormElement(type = FormType.TEXTAREA, listed = true)
	private String note;
//	private Set<EmployeeLeaveHistory> employeeLeaveHistories = new HashSet<EmployeeLeaveHistory>(0);

	private Set<LeaveApprovalHistory> leaveApprovalHistories = new HashSet<LeaveApprovalHistory>();
	
	public Approval() {
	}

	public Approval(ApprovalStatus approvalStatus, ApprovalLevel approvalLevel) {
		this.approvalStatus = approvalStatus;
		this.approvalLevel = approvalLevel;
	}

	public Approval(ApprovalStatus approvalStatus, ApprovalLevel approvalLevel,
			Date date, String note) {
		this.approvalStatus = approvalStatus;
		this.approvalLevel = approvalLevel;
		this.date = date;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPROVAL_STATUS_ID")
	public ApprovalStatus getApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(ApprovalStatus approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPROVAL_LEVEL_ID")
	public ApprovalLevel getApprovalLevel() {
		return this.approvalLevel;
	}

	public void setApprovalLevel(ApprovalLevel approvalLevel) {
		this.approvalLevel = approvalLevel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}



	@Column(name = "NOTE", length = 45)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

//	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
//	@JoinTable(name = "leave_approval_history", joinColumns = { @JoinColumn(name = "APPROVAL_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "EMPLOYEE_LEAVE_HISTORY_ID", nullable = false, updatable = false) })
//	public Set<EmployeeLeaveHistory> getEmployeeLeaveHistories() {
//		return this.employeeLeaveHistories;
//	}
//
//	public void setEmployeeLeaveHistories(
//			Set<EmployeeLeaveHistory> employeeLeaveHistories) {
//		this.employeeLeaveHistories = employeeLeaveHistories;
//	}

	@Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE, org.hibernate.annotations.CascadeType.DELETE_ORPHAN})
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "approval")
	public Set<LeaveApprovalHistory> getLeaveApprovalHistories() {
		return leaveApprovalHistories;
	}

	public void setLeaveApprovalHistories(
			Set<LeaveApprovalHistory> leaveApprovalHistories) {
		this.leaveApprovalHistories = leaveApprovalHistories;
	}
	
	@Override
	public String toString() {
		return "Approval [id=" + id + "]";
	}
}
