package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * CssProperties generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "CSS_PROPERTIES")
public class CssProperties extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String name;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String code;
	private Set<CssPropertiesFields> cssPropertiesFieldses = new HashSet<CssPropertiesFields>(0);
	private Set<CssValues> cssValueses = new HashSet<CssValues>(0);

	public CssProperties() {
	}

	public CssProperties(String name, String code,
			Set<CssPropertiesFields> cssPropertiesFieldses,
			Set<CssValues> cssValueses) {
		this.name = name;
		this.code = code;
		this.cssPropertiesFieldses = cssPropertiesFieldses;
		this.cssValueses = cssValueses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cssProperties")
	public Set<CssPropertiesFields> getCssPropertiesFieldses() {
		return this.cssPropertiesFieldses;
	}

	public void setCssPropertiesFieldses(
			Set<CssPropertiesFields> cssPropertiesFieldses) {
		this.cssPropertiesFieldses = cssPropertiesFieldses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cssProperties")
	public Set<CssValues> getCssValueses() {
		return this.cssValueses;
	}

	public void setCssValueses(Set<CssValues> cssValueses) {
		this.cssValueses = cssValueses;
	}

	@Override
	public String toString() {
		return getName();
	}

}
