package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.Model;
import efs.thesis.common.enumtype.FormType;

/**
 * CssValues generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "CSS_VALUES")
public class CssValues extends Model implements java.io.Serializable {

	private CssValuesId id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private CssClass cssClass;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private CssProperties cssProperties;
	
	@FormElement(type = FormType.TEXTAREA, listed = true)
	private String value;

	public CssValues() {
	}

	public CssValues(CssValuesId id, CssClass cssClass,
			CssProperties cssProperties) {
		this.id = id;
		this.cssClass = cssClass;
		this.cssProperties = cssProperties;
	}

	public CssValues(CssValuesId id, CssClass cssClass,
			CssProperties cssProperties, String value) {
		this.id = id;
		this.cssClass = cssClass;
		this.cssProperties = cssProperties;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cssPropertiesId", column = @Column(name = "CSS_PROPERTIES_ID", nullable = false)),
			@AttributeOverride(name = "cssClassId", column = @Column(name = "CSS_CLASS_ID", nullable = false)) })
	public CssValuesId getId() {
		return this.id;
	}

	public void setId(CssValuesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CSS_CLASS_ID", nullable = false, insertable = false, updatable = false)
	public CssClass getCssClass() {
		return this.cssClass;
	}

	public void setCssClass(CssClass cssClass) {
		this.cssClass = cssClass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CSS_PROPERTIES_ID", nullable = false, insertable = false, updatable = false)
	public CssProperties getCssProperties() {
		return this.cssProperties;
	}

	public void setCssProperties(CssProperties cssProperties) {
		this.cssProperties = cssProperties;
	}

	@Column(name = "VALUE", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public String toString() {
		return getValue();
	}

}
