package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CssValuesId generated by hbm2java
 */
@Embeddable
public class CssValuesId implements java.io.Serializable {

	private int cssPropertiesId;
	private int cssClassId;

	public CssValuesId() {
	}

	public CssValuesId(int cssPropertiesId, int cssClassId) {
		this.cssPropertiesId = cssPropertiesId;
		this.cssClassId = cssClassId;
	}

	@Column(name = "CSS_PROPERTIES_ID", nullable = false)
	public int getCssPropertiesId() {
		return this.cssPropertiesId;
	}

	public void setCssPropertiesId(int cssPropertiesId) {
		this.cssPropertiesId = cssPropertiesId;
	}

	@Column(name = "CSS_CLASS_ID", nullable = false)
	public int getCssClassId() {
		return this.cssClassId;
	}

	public void setCssClassId(int cssClassId) {
		this.cssClassId = cssClassId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CssValuesId))
			return false;
		CssValuesId castOther = (CssValuesId) other;

		return (this.getCssPropertiesId() == castOther.getCssPropertiesId())
				&& (this.getCssClassId() == castOther.getCssClassId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCssPropertiesId();
		result = 37 * result + this.getCssClassId();
		return result;
	}

}
