package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.annotation.validator.NotEmpty;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * Days generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "DAYS")
public class Days extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@NotEmpty
	@FormElement(type = FormType.TEXT, filterable = true, listed = true)
	private String day;
	
	@FormElement(type = FormType.TEXT, filterable = true, listed = true)
	private String code;
	private Set<WorkWeek> workWeeks = new HashSet<WorkWeek>(0);

	public Days() {
	}

	public Days(int id) {
		this.id = id;
	}

	public Days(int id, String day, String code, Set<WorkWeek> workWeeks) {
		this.id = id;
		this.day = day;
		this.code = code;
		this.workWeeks = workWeeks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "DAY", length = 45)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "CODE", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "days")
	public Set<WorkWeek> getWorkWeeks() {
		return this.workWeeks;
	}

	public void setWorkWeeks(Set<WorkWeek> workWeeks) {
		this.workWeeks = workWeeks;
	}

	@Override
	public String toString() {
		return getDay();
	}

}
