package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * Education generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "EDUCATION")
public class Education extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private Employee employee;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private EducationLevel educationLevel;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String institute;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String majorSpecialization;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String year;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private Long gpaScore;
	
	@FormElement(type = FormType.DATE, listed = true)
	private Date startDate;
	
	@FormElement(type = FormType.DATE, listed = true)
	private Date endDate;

	public Education() {
	}

	public Education(Employee employee, EducationLevel educationLevel) {
		this.employee = employee;
		this.educationLevel = educationLevel;
	}

	public Education(Employee employee, EducationLevel educationLevel,
			String institute, String majorSpecialization, String year,
			Long gpaScore, Date startDate, Date endDate) {
		this.employee = employee;
		this.educationLevel = educationLevel;
		this.institute = institute;
		this.majorSpecialization = majorSpecialization;
		this.year = year;
		this.gpaScore = gpaScore;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EDUCATION_LEVEL_ID")
	public EducationLevel getEducationLevel() {
		return this.educationLevel;
	}

	public void setEducationLevel(EducationLevel educationLevel) {
		this.educationLevel = educationLevel;
	}

	@Column(name = "INSTITUTE", length = 45)
	public String getInstitute() {
		return this.institute;
	}

	public void setInstitute(String institute) {
		this.institute = institute;
	}

	@Column(name = "MAJOR_SPECIALIZATION", length = 45)
	public String getMajorSpecialization() {
		return this.majorSpecialization;
	}

	public void setMajorSpecialization(String majorSpecialization) {
		this.majorSpecialization = majorSpecialization;
	}

	@Column(name = "YEAR", length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "GPA_SCORE", precision = 10, scale = 0)
	public Long getGpaScore() {
		return this.gpaScore;
	}

	public void setGpaScore(Long gpaScore) {
		this.gpaScore = gpaScore;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Override
	public String toString() {
		return getId().toString();
	}

}
