package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * FieldsValue generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "FIELDS_VALUE")
@NamedQuery(name = "findFieldValueByFieldsNameAndEntityId", query = "select fv from FieldsValue fv where fv.fields.name = ? and fv.entityId = ?")
public class FieldsValue extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private Fields fields;
	
	@FormElement(type = FormType.TEXTAREA, listed = true)
	private String value;
	
	private Integer entityId;

	public FieldsValue() {
	}

	public FieldsValue(Fields fields) {
		this.fields = fields;
	}

	public FieldsValue(Fields fields, String value) {
		this.fields = fields;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIELDS_ID")
	public Fields getFields() {
		return this.fields;
	}

	public void setFields(Fields fields) {
		this.fields = fields;
	}

	@Column(name = "VALUE", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	@Column(name = "ENTITY_ID", length = 65535)
	public Integer getEntityId() {
		return entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@Override
	public String toString() {
		return getValue();
	}

}
