package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * Holidays generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "HOLIDAYS")
public class Holidays extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private LeavePeriod leavePeriod;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private WorkTimeUnit workTimeUnit;
	
	@FormElement(type = FormType.DATE, listed = true)
	private Date date;
	
	@FormElement(type = FormType.CHECKBOX, listed = true)
	private Boolean repeatsAnnualy;

	public Holidays() {
	}

	public Holidays(LeavePeriod leavePeriod, WorkTimeUnit workTimeUnit) {
		this.leavePeriod = leavePeriod;
		this.workTimeUnit = workTimeUnit;
	}

	public Holidays(LeavePeriod leavePeriod, WorkTimeUnit workTimeUnit,
			Date date, Boolean repeatsAnnualy) {
		this.leavePeriod = leavePeriod;
		this.workTimeUnit = workTimeUnit;
		this.date = date;
		this.repeatsAnnualy = repeatsAnnualy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_PERIOD_ID")
	public LeavePeriod getLeavePeriod() {
		return this.leavePeriod;
	}

	public void setLeavePeriod(LeavePeriod leavePeriod) {
		this.leavePeriod = leavePeriod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WORK_TIME_UNIT_ID")
	public WorkTimeUnit getWorkTimeUnit() {
		return this.workTimeUnit;
	}

	public void setWorkTimeUnit(WorkTimeUnit workTimeUnit) {
		this.workTimeUnit = workTimeUnit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "REPEATS_ANNUALY")
	public Boolean getRepeatsAnnualy() {
		return this.repeatsAnnualy;
	}

	public void setRepeatsAnnualy(Boolean repeatsAnnualy) {
		this.repeatsAnnualy = repeatsAnnualy;
	}

	@Override
	public String toString() {
		return getDate().toString();
	}

}
