package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * L10n generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "L10N")
@NamedQueries(value = {
	@NamedQuery(name = "findL10NById", query = "from L10n l where l.id = ?"),
	@NamedQuery(name = "findL10NByTypeName", query = "from L10n l where l.l10NType.name = ?"),
	@NamedQuery(name = "findL10NByTypeNameAndDefault", query = "from L10n l where l.l10NType.name = ? and l.isDefault = true")
})
public class L10n extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String name;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String code;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private L10NType l10NType;
	
	@FormElement(type = FormType.CHECKBOX, listed = true)
	private Boolean isDefault;
	
	private Set<Translation> translations = new HashSet<Translation>(0);

	public L10n() {
	}

	public L10n(String name, String code) {
		this.name = name;
		this.code = code;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "l10n")
	public Set<Translation> getTranslations() {
		return this.translations;
	}

	public void setTranslations(Set<Translation> translations) {
		this.translations = translations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "L10N_TYPE_ID")
	public L10NType getL10NType() {
		return l10NType;
	}

	public void setL10NType(L10NType l10nType) {
		l10NType = l10nType;
	}

	@Column(name = "IS_DEFAULT")
	public Boolean getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Override
	public String toString() {
		return getName();
	}

}
