package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * ModuleGroup generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "MODULE_GROUP")
public class ModuleGroup extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private ModuleGroup moduleGroup;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String name;
	private Set<ModuleGroup> moduleGroups = new HashSet<ModuleGroup>(0);
	private Set<AccessibleModule> accessibleModules = new HashSet<AccessibleModule>(0);

	public ModuleGroup() {
	}

	public ModuleGroup(ModuleGroup moduleGroup) {
		this.moduleGroup = moduleGroup;
	}

	public ModuleGroup(ModuleGroup moduleGroup, String name,
			Set<ModuleGroup> moduleGroups,
			Set<AccessibleModule> accessibleModules) {
		this.moduleGroup = moduleGroup;
		this.name = name;
		this.moduleGroups = moduleGroups;
		this.accessibleModules = accessibleModules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUP")
	public ModuleGroup getModuleGroup() {
		return this.moduleGroup;
	}

	public void setModuleGroup(ModuleGroup moduleGroup) {
		this.moduleGroup = moduleGroup;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "moduleGroup")
	public Set<ModuleGroup> getModuleGroups() {
		return this.moduleGroups;
	}

	public void setModuleGroups(Set<ModuleGroup> moduleGroups) {
		this.moduleGroups = moduleGroups;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "moduleGroup")
	public Set<AccessibleModule> getAccessibleModules() {
		return this.accessibleModules;
	}

	public void setAccessibleModules(Set<AccessibleModule> accessibleModules) {
		this.accessibleModules = accessibleModules;
	}

	@Override
	public String toString() {
		return getName();
	}

}
