package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * Skills generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "SKILLS")
public class Skills extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private Employee employee;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private Short yearOfExperience;
	
	@FormElement(type = FormType.TEXTAREA, listed = true)
	private String note;

	public Skills() {
	}

	public Skills(Employee employee) {
		this.employee = employee;
	}

	public Skills(Employee employee, Short yearOfExperience, String note) {
		this.employee = employee;
		this.yearOfExperience = yearOfExperience;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "YEAR_OF_EXPERIENCE")
	public Short getYearOfExperience() {
		return this.yearOfExperience;
	}

	public void setYearOfExperience(Short yearOfExperience) {
		this.yearOfExperience = yearOfExperience;
	}

	@Column(name = "NOTE", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Override
	public String toString() {
		return getId().toString();
	}

}
