package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * Subscription generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "SUBSCRIPTION")
public class Subscription extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private Employee employee;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private MembershipPayer membershipPayer;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private Currency currency;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private Membership membership;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private Long subscriptionAmount;
	
	@FormElement(type = FormType.DATE, listed = true)
	private Date commenceDate;
	
	@FormElement(type = FormType.DATE, listed = true)
	private Date renewalDate;

	public Subscription() {
	}

	public Subscription(Employee employee, MembershipPayer membershipPayer,
			Currency currency, Membership membership) {
		this.employee = employee;
		this.membershipPayer = membershipPayer;
		this.currency = currency;
		this.membership = membership;
	}

	public Subscription(Employee employee, MembershipPayer membershipPayer,
			Currency currency, Membership membership, Long subscriptionAmount,
			Date commenceDate, Date renewalDate) {
		this.employee = employee;
		this.membershipPayer = membershipPayer;
		this.currency = currency;
		this.membership = membership;
		this.subscriptionAmount = subscriptionAmount;
		this.commenceDate = commenceDate;
		this.renewalDate = renewalDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEMBERSHIP_PAYER_ID")
	public MembershipPayer getMembershipPayer() {
		return this.membershipPayer;
	}

	public void setMembershipPayer(MembershipPayer membershipPayer) {
		this.membershipPayer = membershipPayer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCY_ID")
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEMBERSHIP_ID")
	public Membership getMembership() {
		return this.membership;
	}

	public void setMembership(Membership membership) {
		this.membership = membership;
	}

	@Column(name = "SUBSCRIPTION_AMOUNT", precision = 10, scale = 0)
	public Long getSubscriptionAmount() {
		return this.subscriptionAmount;
	}

	public void setSubscriptionAmount(Long subscriptionAmount) {
		this.subscriptionAmount = subscriptionAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "COMMENCE_DATE", length = 10)
	public Date getCommenceDate() {
		return this.commenceDate;
	}

	public void setCommenceDate(Date commenceDate) {
		this.commenceDate = commenceDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RENEWAL_DATE", length = 10)
	public Date getRenewalDate() {
		return this.renewalDate;
	}

	public void setRenewalDate(Date renewalDate) {
		this.renewalDate = renewalDate;
	}

	@Override
	public String toString() {
		return getId().toString();
	}

}
