package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * Termination generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "TERMINATION")
public class Termination extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private TerminationReason terminationReason;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private Job job;
	
	@FormElement(type = FormType.DATE, listed = true)
	private Date date;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String note;

	public Termination() {
	}

	public Termination(TerminationReason terminationReason, Job job) {
		this.terminationReason = terminationReason;
		this.job = job;
	}

	public Termination(TerminationReason terminationReason, Job job, Date date,
			String note) {
		this.terminationReason = terminationReason;
		this.job = job;
		this.date = date;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TERMINATION_REASON_ID")
	public TerminationReason getTerminationReason() {
		return this.terminationReason;
	}

	public void setTerminationReason(TerminationReason terminationReason) {
		this.terminationReason = terminationReason;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_ID")
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "NOTE", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Override
	public String toString() {
		return getDate().toString();
	}

}
