package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.Model;
import efs.thesis.common.enumtype.FormType;

/**
 * WorkWeek generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "WORK_WEEK")
public class WorkWeek extends Model implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.TEXT, filterable = true, listed = true)
	private String name;
	
	@FormElement(type = FormType.TEXT, filterable = true, listed = true)
	private String code;
	
	@FormElement(type = FormType.POPUP, filterable = true, listed = true)
	private Days days;
	
	@FormElement(type = FormType.POPUP, filterable = true, listed = true)
	private WorkTimeUnit workTimeUnit;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", length = 45)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DAYS_ID")
	public Days getDays() {
		return days;
	}

	public void setDays(Days days) {
		this.days = days;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WORK_TIME_UNIT_ID")
	public WorkTimeUnit getWorkTimeUnit() {
		return workTimeUnit;
	}

	public void setWorkTimeUnit(WorkTimeUnit workTimeUnit) {
		this.workTimeUnit = workTimeUnit;
	}

	@Override
	public String toString() {
		return getName();
	}

}
