package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * AccessibleModule generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "ACCESSIBLE_MODULE")
@NamedQuery(name = "findAccessibleModuleByName", query = "from AccessibleModule am where am.name = ?")
public class AccessibleModule extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private ModuleGroup moduleGroup;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private Role role;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String name;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String url;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String nextSequenceId;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String prevSequenceId;
	
	private Set<EmployeeAccess> employeeAccesses = new HashSet<EmployeeAccess>(0);
	private Set<Fields> fieldses = new HashSet<Fields>(0);

	public AccessibleModule() {
	}

	public AccessibleModule(ModuleGroup moduleGroup, Role role) {
		this.moduleGroup = moduleGroup;
		this.role = role;
	}

	public AccessibleModule(ModuleGroup moduleGroup, Role role, String name,
			String url, String nextSequenceId,
			Set<EmployeeAccess> employeeAccesses, Set<Fields> fieldses) {
		this.moduleGroup = moduleGroup;
		this.role = role;
		this.name = name;
		this.url = url;
		this.nextSequenceId = nextSequenceId;
		this.employeeAccesses = employeeAccesses;
		this.fieldses = fieldses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCESSIBLE_MODULE_GROUP_ID")
	public ModuleGroup getModuleGroup() {
		return this.moduleGroup;
	}

	public void setModuleGroup(ModuleGroup moduleGroup) {
		this.moduleGroup = moduleGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "NEXT_SEQUENCE_ID", length = 45)
	public String getNextSequenceId() {
		return this.nextSequenceId;
	}

	public void setNextSequenceId(String nextSequenceId) {
		this.nextSequenceId = nextSequenceId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "accessibleModule")
	public Set<EmployeeAccess> getEmployeeAccesses() {
		return this.employeeAccesses;
	}

	public void setEmployeeAccesses(Set<EmployeeAccess> employeeAccesses) {
		this.employeeAccesses = employeeAccesses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "accessibleModule")
	public Set<Fields> getFieldses() {
		return this.fieldses;
	}

	public void setFieldses(Set<Fields> fieldses) {
		this.fieldses = fieldses;
	}
	
	@Column(name = "PREV_SEQUENCE_ID", length = 45)
	public String getPrevSequenceId() {
		return prevSequenceId;
	}

	public void setPrevSequenceId(String prevSequenceId) {
		this.prevSequenceId = prevSequenceId;
	}

	@Override
	public String toString() {
		return getName() + " >" + getUrl();
	}

}
