package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FieldsAttributesId generated by hbm2java
 */
@Embeddable
public class FieldsAttributesId implements java.io.Serializable {

	private int attributesMappingId;
	private int fieldsId;

	public FieldsAttributesId() {
	}

	public FieldsAttributesId(int attributesMappingId, int fieldsId) {
		this.attributesMappingId = attributesMappingId;
		this.fieldsId = fieldsId;
	}

	@Column(name = "ATTRIBUTES_MAPPING_ID", nullable = false)
	public int getAttributesMappingId() {
		return this.attributesMappingId;
	}

	public void setAttributesMappingId(int attributesMappingId) {
		this.attributesMappingId = attributesMappingId;
	}

	@Column(name = "FIELDS_ID", nullable = false)
	public int getFieldsId() {
		return this.fieldsId;
	}

	public void setFieldsId(int fieldsId) {
		this.fieldsId = fieldsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FieldsAttributesId))
			return false;
		FieldsAttributesId castOther = (FieldsAttributesId) other;

		return (this.getAttributesMappingId() == castOther
				.getAttributesMappingId())
				&& (this.getFieldsId() == castOther.getFieldsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAttributesMappingId();
		result = 37 * result + this.getFieldsId();
		return result;
	}

}
