package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FieldsJsScriptId generated by hbm2java
 */
@Embeddable
public class FieldsJsScriptId implements java.io.Serializable {

	private int fieldsId;
	private int jsId;

	public FieldsJsScriptId() {
	}

	public FieldsJsScriptId(int fieldsId, int jsId) {
		this.fieldsId = fieldsId;
		this.jsId = jsId;
	}

	@Column(name = "FIELDS_ID", nullable = false)
	public int getFieldsId() {
		return this.fieldsId;
	}

	public void setFieldsId(int fieldsId) {
		this.fieldsId = fieldsId;
	}

	@Column(name = "JS_ID", nullable = false)
	public int getJsId() {
		return this.jsId;
	}

	public void setJsId(int jsId) {
		this.jsId = jsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FieldsJsScriptId))
			return false;
		FieldsJsScriptId castOther = (FieldsJsScriptId) other;

		return (this.getFieldsId() == castOther.getFieldsId())
				&& (this.getJsId() == castOther.getJsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFieldsId();
		result = 37 * result + this.getJsId();
		return result;
	}

}
