package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * HtmlAttributesMapping generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "HTML_ATTRIBUTES_MAPPING")
public class HtmlAttributesMapping extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private HtmlAttributes htmlAttributes;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private FieldsType fieldsType;
	private Set<FieldsAttributes> fieldsAttributeses = new HashSet<FieldsAttributes>(0);

	public HtmlAttributesMapping() {
	}

	public HtmlAttributesMapping(HtmlAttributes htmlAttributes,
			FieldsType fieldsType) {
		this.htmlAttributes = htmlAttributes;
		this.fieldsType = fieldsType;
	}

	public HtmlAttributesMapping(HtmlAttributes htmlAttributes,
			FieldsType fieldsType, Set<FieldsAttributes> fieldsAttributeses) {
		this.htmlAttributes = htmlAttributes;
		this.fieldsType = fieldsType;
		this.fieldsAttributeses = fieldsAttributeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIELDS_ATTRIBUTES_ID")
	public HtmlAttributes getHtmlAttributes() {
		return this.htmlAttributes;
	}

	public void setHtmlAttributes(HtmlAttributes htmlAttributes) {
		this.htmlAttributes = htmlAttributes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIELDS_TYPE_ID")
	public FieldsType getFieldsType() {
		return this.fieldsType;
	}

	public void setFieldsType(FieldsType fieldsType) {
		this.fieldsType = fieldsType;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "htmlAttributesMapping")
	public Set<FieldsAttributes> getFieldsAttributeses() {
		return this.fieldsAttributeses;
	}

	public void setFieldsAttributeses(Set<FieldsAttributes> fieldsAttributeses) {
		this.fieldsAttributeses = fieldsAttributeses;
	}

	@Override
	public String toString() {
		return getId().toString();
	}

}
