package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * HtmlAttributes generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "HTML_ATTRIBUTES")
public class HtmlAttributes extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String name;
	private Set<HtmlAttributesMapping> htmlAttributesMappings = new HashSet<HtmlAttributesMapping>(0);

	public HtmlAttributes() {
	}

	public HtmlAttributes(String name,
			Set<HtmlAttributesMapping> htmlAttributesMappings) {
		this.name = name;
		this.htmlAttributesMappings = htmlAttributesMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "htmlAttributes")
	public Set<HtmlAttributesMapping> getHtmlAttributesMappings() {
		return this.htmlAttributesMappings;
	}

	public void setHtmlAttributesMappings(
			Set<HtmlAttributesMapping> htmlAttributesMappings) {
		this.htmlAttributesMappings = htmlAttributesMappings;
	}

	@Override
	public String toString() {
		return getName();
	}

}
