package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * JobSpecification generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "JOB_SPECIFICATION")
public class JobSpecification extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP)
	private JobTitle jobTitle;
	
	@FormElement(type = FormType.TEXT)
	private String name;
	
	@FormElement(type = FormType.TEXT)
	private String url;
	
	@FormElement(type = FormType.CHECKBOX)
	private Boolean isDefault;

	public JobSpecification() {
	}

	public JobSpecification(JobTitle jobTitle) {
		this.jobTitle = jobTitle;
	}

	public JobSpecification(JobTitle jobTitle, String name, String url,
			Boolean isDefault) {
		this.jobTitle = jobTitle;
		this.name = name;
		this.url = url;
		this.isDefault = isDefault;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_TITLE_ID")
	public JobTitle getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(JobTitle jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "IS_DEFAULT")
	public Boolean getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Override
	public String toString() {
		return getName();
	}

}
