package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * LeavePeriod generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "LEAVE_PERIOD")
public class LeavePeriod extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String name;
	
	@FormElement(type = FormType.DATE, listed = true)
	private Date startDate;
	
	@FormElement(type = FormType.DATE, listed = true)
	private Date endDate;
	private Set<EmployeeLeaveHistory> employeeLeaveHistories = new HashSet<EmployeeLeaveHistory>(0);
	private Set<Holidays> holidayses = new HashSet<Holidays>(0);

	public LeavePeriod() {
	}

	public LeavePeriod(String name, Date startDate, Date endDate,
			Set<EmployeeLeaveHistory> employeeLeaveHistories,
			Set<Holidays> holidayses) {
		this.name = name;
		this.startDate = startDate;
		this.endDate = endDate;
		this.employeeLeaveHistories = employeeLeaveHistories;
		this.holidayses = holidayses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "END_DATE", length = 45)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "leavePeriod")
	public Set<EmployeeLeaveHistory> getEmployeeLeaveHistories() {
		return this.employeeLeaveHistories;
	}

	public void setEmployeeLeaveHistories(
			Set<EmployeeLeaveHistory> employeeLeaveHistories) {
		this.employeeLeaveHistories = employeeLeaveHistories;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "leavePeriod")
	public Set<Holidays> getHolidayses() {
		return this.holidayses;
	}

	public void setHolidayses(Set<Holidays> holidayses) {
		this.holidayses = holidayses;
	}

	@Override
	public String toString() {
		return getName();
	}

}
