package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * Translation generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "TRANSLATION")
@NamedQuery(name = "findTranslationByI18NAndL10N", query = "from Translation t where t.l10n = ? and t.i18n.key = ?")
public class Translation extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private I18n i18n;
	
	@FormElement(type = FormType.POPUP, listed = true)
	private L10n l10n;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String value;

	public Translation() {
	}

	public Translation(Integer id, I18n i18n, L10n l10n) {
		this.id = id;
		this.i18n = i18n;
		this.l10n = l10n;
	}

	public Translation(Integer id, I18n i18n, L10n l10n, String value) {
		this.id = id;
		this.i18n = i18n;
		this.l10n = l10n;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "I18N_ID")
	public I18n getI18n() {
		return this.i18n;
	}

	public void setI18n(I18n i18n) {
		this.i18n = i18n;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "L10N_ID")
	public L10n getL10n() {
		return this.l10n;
	}

	public void setL10n(L10n l10n) {
		this.l10n = l10n;
	}

	@Column(name = "VALUE", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public String toString() {
		return new StringBuffer(l10n.toString()).append(", ").append(i18n).append(", ").append(value).toString();
	}

}
