package efs.thesis.saas.model;

// Generated Mar 13, 2013 12:38:40 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import efs.thesis.common.annotation.AutoCrud;
import efs.thesis.common.annotation.FormElement;
import efs.thesis.common.db.model.PlainModel;
import efs.thesis.common.enumtype.FormType;

/**
 * WorkTimeUnit generated by hbm2java
 */

@AutoCrud
@Entity
@Table(name = "WORK_TIME_UNIT")
public class WorkTimeUnit extends PlainModel implements java.io.Serializable {

	private Integer id;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String name;
	
	@FormElement(type = FormType.TEXT, listed = true)
	private String code;
	private Set<WorkWeek> workWeeks = new HashSet<WorkWeek>(0);
	private Set<Holidays> holidayses = new HashSet<Holidays>(0);

	public WorkTimeUnit() {
	}

	public WorkTimeUnit(String name, String code, Set<WorkWeek> workWeeks,
			Set<Holidays> holidayses) {
		this.name = name;
		this.code = code;
		this.workWeeks = workWeeks;
		this.holidayses = holidayses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTimeUnit")
	public Set<WorkWeek> getWorkWeeks() {
		return this.workWeeks;
	}

	public void setWorkWeeks(Set<WorkWeek> workWeeks) {
		this.workWeeks = workWeeks;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "workTimeUnit")
	public Set<Holidays> getHolidayses() {
		return this.holidayses;
	}

	public void setHolidayses(Set<Holidays> holidayses) {
		this.holidayses = holidayses;
	}

	@Override
	public String toString() {
		return getName();
	}

}
