package efs.thesis.saas.model.config;

// Generated Apr 26, 2013 7:38:28 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EncryptionKey generated by hbm2java
 */
@Entity
@Table(name = "ENCRYPTION_KEY", catalog = "orangehrm_saas_config")
public class EncryptionKey implements java.io.Serializable {

	private Integer id;
	private Tenants tenants;
	private String encryptionKey;

	public EncryptionKey() {
	}

	public EncryptionKey(Tenants tenants, String encryptionKey) {
		this.tenants = tenants;
		this.encryptionKey = encryptionKey;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TENANTS_ID")
	public Tenants getTenants() {
		return this.tenants;
	}

	public void setTenants(Tenants tenants) {
		this.tenants = tenants;
	}

	@Column(name = "ENCRYPTION_KEY", length = 65535)
	public String getEncryptionKey() {
		return this.encryptionKey;
	}

	public void setEncryptionKey(String encryptionKey) {
		this.encryptionKey = encryptionKey;
	}

}
