package efs.thesis.saas.model.config;

// Generated Apr 26, 2013 7:38:28 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServerInstance generated by hbm2java
 */
@Entity
@Table(name = "SERVER_INSTANCE", catalog = "orangehrm_saas_config")
public class ServerInstance implements java.io.Serializable {

	private Integer id;
	private String name;
	private Byte dbInstanceMax;
	private Set<DbConnection> dbConnections = new HashSet<DbConnection>(0);

	public ServerInstance() {
	}

	public ServerInstance(String name, Byte dbInstanceMax,
			Set<DbConnection> dbConnections) {
		this.name = name;
		this.dbInstanceMax = dbInstanceMax;
		this.dbConnections = dbConnections;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DB_INSTANCE_MAX")
	public Byte getDbInstanceMax() {
		return this.dbInstanceMax;
	}

	public void setDbInstanceMax(Byte dbInstanceMax) {
		this.dbInstanceMax = dbInstanceMax;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serverInstance")
	public Set<DbConnection> getDbConnections() {
		return this.dbConnections;
	}

	public void setDbConnections(Set<DbConnection> dbConnections) {
		this.dbConnections = dbConnections;
	}

}
