package efs.thesis.saas.model.config;

// Generated Apr 26, 2013 7:38:28 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DbConnection generated by hbm2java
 */
@Entity
@Table(name = "DB_CONNECTION", catalog = "orangehrm_saas_config")
public class DbConnection implements java.io.Serializable {

	private Integer id;
	private Tenants tenants;
	private ServerInstance serverInstance;
	private String url;
	private String username;
	private String password;

	public DbConnection() {
	}

	public DbConnection(Tenants tenants, ServerInstance serverInstance,
			String url, String username, String password) {
		this.tenants = tenants;
		this.serverInstance = serverInstance;
		this.url = url;
		this.username = username;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TENANTS_ID")
	public Tenants getTenants() {
		return this.tenants;
	}

	public void setTenants(Tenants tenants) {
		this.tenants = tenants;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVER_INSTANCE_ID")
	public ServerInstance getServerInstance() {
		return this.serverInstance;
	}

	public void setServerInstance(ServerInstance serverInstance) {
		this.serverInstance = serverInstance;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "USERNAME", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
